#pragma once

// foo_netease 资源 ID。

#define IDD_NETEASE_PREFS   101
#define IDD_NETEASE_LOGIN   102

#define IDC_NETEASE_HINT        1001
#define IDC_NETEASE_STATUS      1002
#define IDC_NETEASE_LOGIN_BTN   1004
#define IDC_NETEASE_LOGOUT_BTN  1005
#define IDC_NETEASE_QUALITY     1006
#define IDC_NETEASE_ACCOUNT     1007
#define IDC_NETEASE_CLEAR       1008
#define IDC_NETEASE_STATUS_LBL  1009
#define IDC_NETEASE_ACCOUNT_LBL 1014
#define IDC_NETEASE_QUALITY_LBL 1015
#define IDC_NETEASE_BROWSE_BTN  1018
#define IDC_NETEASE_PANEL_BTN   1050
#define IDC_NETEASE_COVER_NOW   1051
#define IDC_NETEASE_FOLLOW_CURSOR 1052

#define IDC_LOGIN_QR            1010
#define IDC_LOGIN_STATUS        1011
#define IDC_LOGIN_HINT          1012
#define IDC_LOGIN_REFRESH       1013

// ---- M4 浏览窗口 ----
#define IDD_NETEASE_BROWSE      105

#define IDC_BROWSE_PLAYLISTS    1040
#define IDC_BROWSE_TRACKS       1041
#define IDC_BROWSE_SEARCH       1042
#define IDC_BROWSE_SEARCH_BTN   1043
#define IDC_BROWSE_REFRESH      1044
#define IDC_BROWSE_ADD          1045
#define IDC_BROWSE_REPLACE      1046
#define IDC_BROWSE_STATUS       1047
#define IDC_BROWSE_ACCOUNT      1048

